In [56]:
import pandas as pd

data = {
    "Student_ID": [
    101, 102, 103, 104, 105,106,
    106, 107, 108, 109, 110,
    111, 112, 113, 114, 115,
    116, 117, 118, 119, 120
    ],
    "Attendance_percentage": [
        95, 87, 72, 96, 68, 91,91, 78, 84, 55, 93,
        74, 88, 62, 97, 80, 90, 70, 85, 58, 92
    ],

    "Previous_sem_marks": [
        88, 76, 65, 92, 58,85,85, 70, 79, 45, 89,
        63, 81, 50, 94, 72, 86, 60, 77, 48, 87
    ],

    "Internal_assessment": [
        91, 82, 70, 94, 62, 88,88, 74, 81, 52, 90,
        68, 85, 56, 96, 76, 89, 64, 80, 51, 91
    ],

    "Assignment_score": [
        90, 78, 68, 95, 60, 86,86, 72, 80, 48, 92,
        65, 83, 54, 95, 75, 87, 62, 79, 50, 89
    ],

    "Study_Hours_Day": [
        6, 5, 3, 7, 2, 6,6, 4, 5, 1, 7,
        3, 5, 2, 8, 4, None, 3, 5, 1, 7
    ],

    "Class_Participation": [
        9, 8, 6, None, 5, 9,9, 7, 8, 3, 10,
        6, 9, 4, 10, 7, 9, 5, 8, 4, 9
    ],

    "Completed_assignments": [
        10, 9, 7, 10, 6, 10,10, 8, 9, 4, 10,
        7, 9, 5, None, 8, 10, 6, 9, 4, 10
    ],

    "Previous_exam_performance": [
        92, 80, 67, 96, 55, 89,89, 71, 82, 42, 94,
        61, 84, 48, 97, 74, 91, 58, 79, 45, 90
    ],

    "Learning_activities": [
        "High", "Low", "Medium", "High", "Low",
        "High","High", "Medium", "High", "Low", "High",
        "Medium", "High", "High", "High", "Medium",
        "High", "Medium", "High", "Low", "High"
    ],

    "Socio_Academic_factors": [
        "Good", "Good", "Average", "Good", "Average",
        "Good","Good", "Average", "Good", "Challenging", "Good",
        "Average", "Good", "Challenging", "Good", "Average",
        "Good", "Average", "Good", "Challenging", "Good"
    ],

    "Final_performance": [
        "Excellent", "Very Good", "Good", "Excellent", "Average",
        "Excellent","Excellent", "Good", "Very Good", "Needs Improvement", "Excellent",
        "Good", "Very Good", "Needs Improvement", "Excellent", "Good",
        "Excellent", "Average", "Very Good", "Needs Improvement", "Excellent"
    ]
}

df = pd.DataFrame(data)
display(df)

display("Head values:",df.head())
display("Tail values:",df.tail())
print("Number of columns and Rows:", df.shape)
display("Datatypes:", df.dtypes)
numerical_cols = df.select_dtypes(include=['number']).columns
display(numerical_cols)
categorical_cols = df.select_dtypes(include=['object']).columns
display(categorical_cols)
display(df.isnull())
display(df.isnull().sum())
df["Study_Hours_Day"] = df["Study_Hours_Day"].fillna(df["Study_Hours_Day"].mean())
df["Class_Participation"] = df["Class_Participation"].fillna(df["Class_Participation"].mean())
df["Completed_assignments"]=df["Completed_assignments"].fillna(df["Completed_assignments"].mean())
df["Previous_exam_performance"] = df["Previous_exam_performance"].fillna(df["Previous_exam_performance"].mean())
display(df)
display("Duplicated values:",df.duplicated())
display(df.duplicated().sum())
df=df.drop_duplicates()
display(df)
print("Count values:",df["Previous_exam_performance"].value_counts())
print("Mean value:",df["Student_ID"].mean())
print("Median value:",df["Attendance_percentage"].median())
print("Mode value:",df["Study_Hours_Day"].mode())
marks_range = df["Class_Participation"].max() - df["Class_Participation"].min()
print("Marks_range",marks_range)
print("Variance",df["Class_Participation"].var())
print("Standard Deviation",df["Class_Participation"].std())

,Student_ID,Attendance_percentage,Previous_sem_marks,Internal_assessment,Assignment_score,Study_Hours_Day,Class_Participation,Completed_assignments,Previous_exam_performance,Learning_activities,Socio_Academic_factors,Final_performance
0,101,95,88,91,90,6.0,9.0,10.0,92,High,Good,Excellent
1,102,87,76,82,78,5.0,8.0,9.0,80,Low,Good,Very Good
2,103,72,65,70,68,3.0,6.0,7.0,67,Medium,Average,Good
3,104,96,92,94,95,7.0,NaN,10.0,96,High,Good,Excellent
4,105,68,58,62,60,2.0,5.0,6.0,55,Low,Average,Average
5,106,91,85,88,86,6.0,9.0,10.0,89,High,Good,Excellent
6,106,91,85,88,86,6.0,9.0,10.0,89,High,Good,Excellent
7,107,78,70,74,72,4.0,7.0,8.0,71,Medium,Average,Good
8,108,84,79,81,80,5.0,8.0,9.0,82,High,Good,Very Good
9,109,55,45,52,48,1.0,3.0,4.0,42,Low,Challenging,Needs Improvement
10,110,93,89,90,92,7.0,10.0,10.0,94,High,Good,Excellent
11,111,74,63,68,65,3.0,6.0,7.0,61,Medium,Average,Good
12,112,88,81,85,83,5.0,9.0,9.0,84,High,Good,Very Good
13,113,62,50,56,54,2.0,4.0,5.0,48,High,Challenging,Needs Improvement
14,114,97,94,96,95,8.0,10.0,NaN,97,High,Good,Excellent
15,115,80,72,76,75,4.0,7.0,8.0,74,Medium,Average,Good
16,116,90,86,89,87,NaN,9.0,10.0,91,High,Good,Excellent
17,117,70,60,64,62,3.0,5.0,6.0,58,Medium,Average,Average
18,118,85,77,80,79,5.0,8.0,9.0,79,High,Good,Very Good
19,119,58,48,51,50,1.0,4.0,4.0,45,Low,Challenging,Needs Improvement
20,120,92,87,91,89,7.0,9.0,10.0,90,High,Good,Excellent

'Head values:'

,Student_ID,Attendance_percentage,Previous_sem_marks,Internal_assessment,Assignment_score,Study_Hours_Day,Class_Participation,Completed_assignments,Previous_exam_performance,Learning_activities,Socio_Academic_factors,Final_performance
0,101,95,88,91,90,6.0,9.0,10.0,92,High,Good,Excellent
1,102,87,76,82,78,5.0,8.0,9.0,80,Low,Good,Very Good
2,103,72,65,70,68,3.0,6.0,7.0,67,Medium,Average,Good
3,104,96,92,94,95,7.0,NaN,10.0,96,High,Good,Excellent
4,105,68,58,62,60,2.0,5.0,6.0,55,Low,Average,Average

'Tail values:'

,Student_ID,Attendance_percentage,Previous_sem_marks,Internal_assessment,Assignment_score,Study_Hours_Day,Class_Participation,Completed_assignments,Previous_exam_performance,Learning_activities,Socio_Academic_factors,Final_performance
16,116,90,86,89,87,NaN,9.0,10.0,91,High,Good,Excellent
17,117,70,60,64,62,3.0,5.0,6.0,58,Medium,Average,Average
18,118,85,77,80,79,5.0,8.0,9.0,79,High,Good,Very Good
19,119,58,48,51,50,1.0,4.0,4.0,45,Low,Challenging,Needs Improvement
20,120,92,87,91,89,7.0,9.0,10.0,90,High,Good,Excellent

Number of columns and Rows: (21, 12)

'Datatypes:'

Student_ID                     int64
Attendance_percentage          int64
Previous_sem_marks             int64
Internal_assessment            int64
Assignment_score               int64
Study_Hours_Day              float64
Class_Participation          float64
Completed_assignments        float64
Previous_exam_performance      int64
Learning_activities           object
Socio_Academic_factors        object
Final_performance             object
dtype: object

Index(['Student_ID', 'Attendance_percentage', 'Previous_sem_marks',
       'Internal_assessment', 'Assignment_score', 'Study_Hours_Day',
       'Class_Participation', 'Completed_assignments',
       'Previous_exam_performance'],
      dtype='object')

Index(['Learning_activities', 'Socio_Academic_factors', 'Final_performance'], dtype='object')

,Student_ID,Attendance_percentage,Previous_sem_marks,Internal_assessment,Assignment_score,Study_Hours_Day,Class_Participation,Completed_assignments,Previous_exam_performance,Learning_activities,Socio_Academic_factors,Final_performance
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,True,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,True,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False

Student_ID                   0
Attendance_percentage        0
Previous_sem_marks           0
Internal_assessment          0
Assignment_score             0
Study_Hours_Day              1
Class_Participation          1
Completed_assignments        1
Previous_exam_performance    0
Learning_activities          0
Socio_Academic_factors       0
Final_performance            0
dtype: int64

,Student_ID,Attendance_percentage,Previous_sem_marks,Internal_assessment,Assignment_score,Study_Hours_Day,Class_Participation,Completed_assignments,Previous_exam_performance,Learning_activities,Socio_Academic_factors,Final_performance
0,101,95,88,91,90,6.0,9.00,10.00,92,High,Good,Excellent
1,102,87,76,82,78,5.0,8.00,9.00,80,Low,Good,Very Good
2,103,72,65,70,68,3.0,6.00,7.00,67,Medium,Average,Good
3,104,96,92,94,95,7.0,7.25,10.00,96,High,Good,Excellent
4,105,68,58,62,60,2.0,5.00,6.00,55,Low,Average,Average
5,106,91,85,88,86,6.0,9.00,10.00,89,High,Good,Excellent
6,106,91,85,88,86,6.0,9.00,10.00,89,High,Good,Excellent
7,107,78,70,74,72,4.0,7.00,8.00,71,Medium,Average,Good
8,108,84,79,81,80,5.0,8.00,9.00,82,High,Good,Very Good
9,109,55,45,52,48,1.0,3.00,4.00,42,Low,Challenging,Needs Improvement
10,110,93,89,90,92,7.0,10.00,10.00,94,High,Good,Excellent
11,111,74,63,68,65,3.0,6.00,7.00,61,Medium,Average,Good
12,112,88,81,85,83,5.0,9.00,9.00,84,High,Good,Very Good
13,113,62,50,56,54,2.0,4.00,5.00,48,High,Challenging,Needs Improvement
14,114,97,94,96,95,8.0,10.00,8.05,97,High,Good,Excellent
15,115,80,72,76,75,4.0,7.00,8.00,74,Medium,Average,Good
16,116,90,86,89,87,4.5,9.00,10.00,91,High,Good,Excellent
17,117,70,60,64,62,3.0,5.00,6.00,58,Medium,Average,Average
18,118,85,77,80,79,5.0,8.00,9.00,79,High,Good,Very Good
19,119,58,48,51,50,1.0,4.00,4.00,45,Low,Challenging,Needs Improvement
20,120,92,87,91,89,7.0,9.00,10.00,90,High,Good,Excellent

'Duplicated values:'

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
dtype: bool

np.int64(1)

,Student_ID,Attendance_percentage,Previous_sem_marks,Internal_assessment,Assignment_score,Study_Hours_Day,Class_Participation,Completed_assignments,Previous_exam_performance,Learning_activities,Socio_Academic_factors,Final_performance
0,101,95,88,91,90,6.0,9.00,10.00,92,High,Good,Excellent
1,102,87,76,82,78,5.0,8.00,9.00,80,Low,Good,Very Good
2,103,72,65,70,68,3.0,6.00,7.00,67,Medium,Average,Good
3,104,96,92,94,95,7.0,7.25,10.00,96,High,Good,Excellent
4,105,68,58,62,60,2.0,5.00,6.00,55,Low,Average,Average
5,106,91,85,88,86,6.0,9.00,10.00,89,High,Good,Excellent
7,107,78,70,74,72,4.0,7.00,8.00,71,Medium,Average,Good
8,108,84,79,81,80,5.0,8.00,9.00,82,High,Good,Very Good
9,109,55,45,52,48,1.0,3.00,4.00,42,Low,Challenging,Needs Improvement
10,110,93,89,90,92,7.0,10.00,10.00,94,High,Good,Excellent
11,111,74,63,68,65,3.0,6.00,7.00,61,Medium,Average,Good
12,112,88,81,85,83,5.0,9.00,9.00,84,High,Good,Very Good
13,113,62,50,56,54,2.0,4.00,5.00,48,High,Challenging,Needs Improvement
14,114,97,94,96,95,8.0,10.00,8.05,97,High,Good,Excellent
15,115,80,72,76,75,4.0,7.00,8.00,74,Medium,Average,Good
16,116,90,86,89,87,4.5,9.00,10.00,91,High,Good,Excellent
17,117,70,60,64,62,3.0,5.00,6.00,58,Medium,Average,Average
18,118,85,77,80,79,5.0,8.00,9.00,79,High,Good,Very Good
19,119,58,48,51,50,1.0,4.00,4.00,45,Low,Challenging,Needs Improvement
20,120,92,87,91,89,7.0,9.00,10.00,90,High,Good,Excellent

Count values: Previous_exam_performance
92    1
80    1
67    1
96    1
55    1
89    1
71    1
82    1
42    1
94    1
61    1
84    1
48    1
97    1
74    1
91    1
58    1
79    1
45    1
90    1
Name: count, dtype: int64
Mean value: 110.5
Median value: 84.5
Mode value: 0    5.0
Name: Study_Hours_Day, dtype: float64
Marks_range 7.0
Variance 4.449177631578947
Standar Deviation 2.109307381957155